#pragma once

enum bvr_editor_flag_e
{
    BVR_EDITOR_MESH,
    BVR_EDITOR_SHADER,
    BVR_EDITOR_TEXTURE,
    BVR_EDITOR_TEXTURE_ARRAY,

    BVR_EDITOR_CAMERA,
    BVR_EDITOR_ASSETS,
    BVR_EDITOR_USER,
    BVR_EDITOR_PIPELINE,
    BVR_EDITOR_GLOBAL_ILL,
    BVR_EDITOR_ACTOR,
    BVR_EDITOR_COLLIDER,
    BVR_EDITOR_LANDSCAPE,
};
