/* Automatically generated by configure - do not modify */

#define TCC_VERSION "0.9.27"
#define CONFIG_TCCDIR ""
#define TCC_LIBTCC1 "" 
#define CONFIG_LDDIR  ""
#define HOST_OS       "Windows"
#define HOST_CPU      "x86_64"
#define CONFIG_TCC_STATIC 1

#define TCC_TARGET_X86_64
#define TCC_TARGET_PE